services:
  poker-score:
    image: registry.cn-hangzhou.aliyuncs.com/wufly632/poker-score:latest
    container_name: poker-score-app
    ports:
      - "127.0.0.1:3268:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./db/custom.db
    volumes:
      # 持久化数据库文件
      - ./data/db:/app/db
      # 持久化日志
      - ./data/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - poker-network

networks:
  poker-network:
    driver: bridge
