version: '3.8'

services:
  poker-score:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./db/custom.db
    volumes:
      # 持久化数据库文件
      - ./db:/app/db
      # 持久化日志
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - poker-network

  # 可选：添加 Caddy 作为反向代理
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-data:/data
      - ./caddy-config:/config
    networks:
      - poker-network
    depends_on:
      - poker-score
    restart: unless-stopped

networks:
  poker-network:
    driver: bridge

volumes:
  caddy-data:
  caddy-config: